
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                      
                                                                                        ` ```````````                                                                                                                                 
                                                                          ``.--::/++++++++++ooooooo++/:-.``                                                                                                                           
                                                                    ``.-:/osyyhhhhhhhhhhhhhhhhhhhhhhhhhhyo/:-..``  `                                                                                                                  
                                                                ``.-/+shhhhhhhhhyhhhhhhhhhhhhhhyyyyyyyyhhhhyysss+/-`                                                                                                                  
                                                              `.:+syhhhhhhhhhyyhhhhhhhhhhhhhhhhhhhhyyyyhhhyyhhhhhhy:``                                                                                                                
                                                            `-/syhhhhhyyyyhhhhhhhyyyyyyyyyhhhhhhyyyyyyyhhhhyyyyyhhhh/.``                                                                                                              
                                                          `-oyhhhhyhhhhyhhhyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhy+:-.``                                                                                                           
                                                         `:sdhhyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhs/. `                                                                                                        
                                                        `:shhyhyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddo:``                                                                                                       
                                                       `-shhhyhyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhy/`                                                                                                       
                                                      `:syhhyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhs.`                                                                                                      
                                                     `:yhhyyhyhhhhhhhhhhhhhhhhhhhhhhhhhhyyhhhhhhhhhhhhhhhhhhhhhhhhhhhyyhhhhhhy:.`   `                                                                                                 
                                                     `+hhyhhhyhhhhhhhhhhhhhhhhhhhhhhyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhs:``` `                                                                                                 
                                                     .shhyhhhyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhy+:.`                                                                                                  
                                                    `-yhhhyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhs+-`                                                                                                
                                                   `:hhyhhyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh+`                                                                                               
                                               `  `-shhhhhhhhhhhhhhhhhhhhhhhhhhhyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhydh+.                                                                                              
                                                 `:ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdo.                                                                                              
                                               `./yhdhdhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyysyyyyyyyyyyyyyyyyyyyyyhhyyhhhhhhhhhhhhhdhhhhdo.                                                                                              
                                               `/hddhddddddddddhhyysoo++/:::::::://::---::::::::::::::::://+/:///++/:////+++++osyyhhhh/`                                                                                              
                                              `.+hddddddddddhyso+/::-----------:::::::::::----:::::::::::://::::///:::::::::::::///oyo.`                                                                                              
                                              `-+yhhdddddddhyo+//::::----------:::-:---------------:::::::::::::::::-------:::---:::-.`                                                                                               
                                              `.://+ooshhdds/:////:::-----------:----:::::::::::::::::::::::::::::::::::::::::::::::.                                                                                                 
                                              `-::--::/+osys:-:////::-------------::::::::///////////////:::::::://:::::::////:::::-`                                                                                                 
                                              `:////:::::///---:///:::::---------::::::://////////////////////////++///////////::::.`                                                                                                 
                                              `:+++++++/://:--:::::::::-----------::::/++osyyyyyo+sso+//////://+syyhyso+////::::::-.`                                                                                                 
                                              `-:/+++oooo+/:--------:::----------::::/ooyddhdddhhsoyso+///:://ohmddmdhhs//+/::::::--`                                                                                                 
                                               `.:+++ooooo+/:---::--::::---------:::://oymddmmmdmysyso+///////+ymmmNmdhs+++::::::---.                                                                                                 
                                                `.:+++oo+/::/:------::::---------::::::/+oyhhdddhsoo+///////////osyhhyso+//:::------.`                                                                                                
                                                 `.://+++/:://:----::::::-----:::::::::::::////////////////////////////////:::----:--`                                                                                                
                                                  `-///++/:://:---:::/::::----::::::::::::::::://///////////////:::::::////::::------`                                                                                                
                                                  ``-/://////+/:--:://::::::::::::::::::::::::::://///////////:::::::::::://::::-----`                                                                                                
                                                    `-:::://+oo::-:://::::::::::::::::::::::::::::///////////:::::::::::::::::::-----``                                                                                               
                                                     .:::://+oo/:--:://::::::::::::::::::::::--::://///////:::::::::::::::::::::-----``                                                                                               
                                                      -:::/++/:::::::://::::::::::::::::::::::::::://////:::/::::::::::::::::::---:---`                                                                                               
                                                      .::/++/:-::::::::///:::--::::::::::::::::::://////:::///:::::::::::::::::--:::::.                                                                                               
                                                      `-:/oo+::::::::::::///::::::::::::::::://///////////////::////::::::::::---::-::-`                                                                                              
                                                       `.:/os+:::::::::-::://///::::::::::::::::///++oooo++++++++o++//::::::---------:-`                                                                                              
                                                      ``-+ymmo:::::::::-:::::////:::::::::::::::::::://++ooooo+++++//::------------:::-`                                                                                              
                                                    `-+ymmNNd+::::::::::::::::::::::::::::::::::::/::::://///////::::--------------::/-`                                                                                              
                                               ` `.-+mmmmNNmd+::::::::::::::::::-:::::::::://////////////////////////:::::::::---::::/:`                                                                                              
                                               `./sdNmNNmmmNdo::::::::::::::::::::::::////+++//++oosyyyhhhyyyysssssoo//::--:----:::::/:`                                                                                              
                                             `.+hmmNmmmmmmmmmh/:::::::::::::::::::::://///////////+++oosssooooooo+++/::---------:::--//`                                                                                              
                                        `   .+hmNmmNmmmmmmmmmms/::::::--::::::::::::::::///////////+++++++++/++ooo+/:---------:::::--/:`                                                                                              
                                         ``:hmmmmmNNmmmmmmmmmms/::::::::::::::::::::::::::::///////++++++++++++//:::::::::::::---::::/:`                                                                                              
                                        `-smNNNNNNNNNmmmmmmmmmdy/:-:::::::::::::::::::::::::::://////////////::::://///:::::::--::--:+:`                                                                                              
                                      `.+dNNNNmmNNNNNNNNmmmmmmNds/::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::--:--:::`                                                                                               
                                     .+hmmNNNNNNNNNNNNNNNmmmmmmmmdy+:::-::::----------::::::::::::::::::::::::::::::::::::::----------.`                                                                                              
                                   `+hNNNNNNNNNNNNNNNNNNmmmmmmmmNmmds::::::-----------:::::::::::::::::::::::--------:::---------------`                                                                                              
                                 `.+dNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmho/::::-------------:::::::::::---------------------------------.:s+-.`         ```                                                                               
                               `./hmNmNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmy/:::----------------------------------------------------------omNdyo+/:///+ossoo+/:.                                                                           
                              `-odmmmmmmNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmms:::---------------------------------------------------------/yNNNNNmmmmmmmmmNNNNNd+`                                                                          
                              .+dmdmdmmmNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmm+:----::------------------------------------:--------------/sdNNNNNNNNmmmmmmmmmmmNy:`                                                                         
                             `:ydmddddmmmmNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmh+:-----::-----------------------------------------------:+yNNNNNNNNNNmmmmmmmmmmmNdo.           `````````                                                     
                             -sdddmdmmmmmmmNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmhso/:--:::----------------------------------------------:odNNNNNNNNNNmmmmmmmdddhddh+.```````..--::::://::-.`````                                             
                            `/ydddddddddmmmmmNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmdho:--::::------------------------------------------:/oymNNNNNNNNNNmmmmmdhysoo++++:::--:::://////////+oo++//:-..``                                         
                           `:ydddddmddmmmmmmmNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmNmh+-----------------------------------------------:odmNNNNNNNNNNNNmmmmdhyso++////////////////////++///+oooooo+/::.``                                      
                          `ohmmdmmmmdmmmmmmmmmmmNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmdyooo+/:::::--------------------------.---------/ymNNNNNNNNNNNNmmmmmmhso++//////////////////////+oooooo++++ooo++:.                                      
                        `.odmmmmmmdhhhdmmmmmmNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmdys+/:----------------------------------:/ohmNNNNNNNNNNNNmmmmmmhso+/////////////////++++/////+ooooooo++++//-`                                     
                       `.ommmmmmdhhysossyhdmmNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmdhysssssso/:::-----------------:/ooo+ohdmNNNNNNNNNNNNNmmmmmmdso///////////////////+osssoo+++++++++ooo+//:.`                                    
                       `/mmmNNmmhsso+//+++oshhddmmmddhhddmmmmmmmdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhyo/:-------------/+sydmmddmNNmmNNNNNNNNNNNNmmmmmmmds//////////////////:://oosssossoo++/+++++++/.                                    
                       `:dmmmmmdyo++////////+++ooooo++++++oooosoooooyddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdhhyyyyyyyyyyyhdmmmmmmmmmmmmmmNNNNNNNNNNNmmmmmmmNmdhyso++///////////////////++oooo+oo++/////:.                                    
                       `-hNmmNmdy+////////////////++++++++///+++++//+sdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNmmmmmmmmmmmmmmmmNmNNNNNNNNNmmmNmmmNNNNNmdy+-.://////////////////////:::://////:.`                                   
                        -yNmmmmmho:///////////////////+++++++++o+++/+sdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNmmmmNNNNNNy:````.:///////::::::::///////::-..--::.`                                   
                        `/Nmmmmmdo:://///////////////////+oooyhdhdhhdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdmNNNNNNNNNNNNmmmmNNNNNh+.    ``-://///-.````..---::::///.``````                                    
                        `:mmmmmmds:/://////////////////////++oyhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdo:smNNNNNNNNNNNmmmNNmy+-`       ``-://+/.``      ``..--::.`                                         
                        `-mNNmmmds///////////////+++++///////+++osyhdmmmmmmmmmmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNd+``./oyhdmNNNNNNNNNm+``           `.:/++/-`  `                                                      
                         .dNNmdddh+///////////////++ossssoo+++/////++osydmmmmmmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmd/   ````..:/+osyyso:```            ``-/////-``                                                      
                         `sNNNmmmdo/////////////////+oosyyyyyyo++++/////+hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNh:             ````                    .-:/++/-`                                                     
                         `:NNNNNNmd+/////////////////+++oosydmmddhyso++/ohmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmms-                                    ` `.-://+:`                                                    
                          `smNNNNNNh////////////++++/////++ooydmNNmmmmmddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNmy:   `                                   ` ``-://.`                                                   
                           `:+oo+/-``-/////://///+osssoo+///+++oshdmmddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmo-`                                           ``..                                                     
                                     `.:///////////+osyyyso++/////++++oymmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNmNdo.                                                                                                      
                                       .-////+/+++++++ossyyyys++++++//+ymNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNmmh:`                                                                                                       
                                        `-/++/+oosssoo++oossyhdddddddhdmNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmho:.`                                                                                                        
                                          `-:+/+oossyyys+++++oosydmNNmmmmmmmmmmmmmmmmmNmNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmms.                                                                                                           
                                            ``--:/+oossyhhyso+++/+oydmmmmmmmmmmmmmmmmmmmNmNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmNd+`                                                                                                          
                                               `:o/-/+oosyhhhyo/////smmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmms`                                                                                                          
                                               .oo.`/hso+++osyhhs++shmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmh.                                                                                                          
                                               /+- `+Nmdho///++hdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmd:`                                                                                                         
                                             `.+/` .yNmmmmhsooydmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmo`                                                                                                         
                                              :/- `:mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmy`                                                                                                         
                                             `+:` .+mmmmmmmmmmmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmy`                                                                                                         
                                             `-.  `:dNmmmmmmmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhs+: `                                                                                                        
                                                  `-hNmmmmmmmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmh/`                                                                                                            
                                             `     `:ohmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddmy/                                                                                                             
                                                   ` `:yddmddmdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddddh+.                                                                                                             
                                                     ``:sdddddddddddddddddddddddddmmmddmhydmmmmmmmmmmmmmmmmmmmmddddddmy:                                                                                                              
                                                        -sdddddddddddddddddddddddmmmmmmm/./ymmmmmmmmmmmmmmmmddddddddddo.                                                                                                              
                                                         :ymdddddddddddddddddddddmdddmmy. `+dmmmmmmmmmmmmmdddddddddddy:`                                                                                                              
                                                         `:ydddddddddddddddddddddddddmd+`  :ymmmmmmmmmmmmmdddddddddddo.                                                                                                               
                                                          `/hddddddddddddddddddddddddmh-   .ommNmmmmmmmmmmddddddddddd+.                                                                                                               
                                                           -ymdddddddddddddddddddddddds`   `odmmmmmmmmmmmmddddddddddd/`                                                                                                               
                                                           .smddddddddddddddddddddddmh/`   :ymNmmmmmmmmmmddddmmmddddy-                                                                                                                
                                                           .omdddddddddddddddddddddddh/`.-+hmNNmmmmmmmmmmddddddddddd/`                                                                                                                
                                                          `-ymdddddddddddddddddddddddh+ohmmmmmmmmmmmmmmmmddddddddddy-                                                                                                                 
                                                       ```-odddddddddddddddddddddddmh+-sNNNNmNNmmmmmmmmmmddddddddddh/-``                                                                                                              
                                                      .ossydmddddddddddddddddddddddmh/`:mMMNNNNNNmmmmmmmmmdddmmmmmmMNms:`                                                                                                             
                                                      .hNNNmmmdddddddddddddddddddddmdy/-+NMNNNNNNNNNNNmmmmmmmmmmmmmNNNs-                                                                                                              
                                                       /dNNNNmmmmmmmmmmmddddddddddmNNmmmdmNNNNNNNNMNNNNNNNNNNNNNNNNNNo-`  `                                                                                                           
                                                       .smNNNmNNNNNmmmmmmmmmmmmmmmNNNNNNo+dNNNNNNNNNNNNNNNNNNNNNNNNMo.      `                                                                                                         
                                                        :hNNNmNNNNNNNNNNNNNNNNNNNNNNNNNy``smNNNNNNNNNNNNNNNNNNNNNNNh.                                                                                                                 
                                                        .oNNNmNNNNNNNNNNNNNNNNNNNNNmNNh-` :hNNNNNNNNNNNNNNNNmNNNNNd-                                                                                                                  
                                                         :hMNNNNNNNNNNNNNNNNNNNNNNNNNh/   `omNNNNNNNNNNNNNNNNNNNNd:`                                                                                                                  
                                                  ```` ` .oNNNmNNNNNNNNNNNNNNNNNNNNNd+`````:hMNNNNNNNNNNNNNNNNNNd+                                                                                                                    
                                          ````````........:hMmNNNNNNNNNNNNNNNNNNNNNmo-.....:yNNNNNNNNNNNNNNNNNNmo.`                                                                                                                   
                                        ````......---------oNNNNNNNNNNNNNNNNNNNNNNms-------:yNNNNNNNNNNNNNNNNNNd/``````````````````````````                                                                                           
                                       ````.....-----------/yMNNNNNNNNNNNNNNNNNNNNs:.------:sNMNNNNNNNNNNNNNNNmy:..````````....`````````````````                                                                                      
                                        ```....-------:----:sMNNNNNNNNNNNNNNNNNNMy:----::--+hNNNNNNNNNNNNNNNNNmy/-.....................````````````                                                                                   
     ``````````````````````            ```....----::::::::-:oNNNNNNNNNNNNNNNNNNNm+-.---:-:odNNNNNNNNNNNNNNNNNNNNds:........................``````````````                                                                             
    ````````````````````````````````````....----::::::/:::::+NNNNNNNNNNNNNNNNNNMh:-----::omNNNNNNNNNNNNNNNNNNNNNNNds:-..........................````````````````````````                                                              
    ````............``````````````````...-----::::////////::oNNNNNNNNNNNNNNNNNNMy-----:::hNNNNNNNNNNNNNNNNNNNNNNNNNNmhs+/--..............................``````````````````                                                           
    ````............................`...-----::::://///////sdNNNNNNNNNNNNNNNNNNNmy/:::::/dNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmdhyo+:-.....................................```````````````                                                  
    ````...............................------::::://///::+yNNNNNNNNNNNNNNNNNNNNNMNmho/::/hNMNNNNNNMNNNNNNNNNNNNNNNNNNNNNNNNNNNdo:........................................````````````                                                 
    ````...........--................--------:::::::::::/yNNNNNNNNNNNNNNNNNNNNNNNNNNmhs//yNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNms:.................................................````                                               
    ```....----------------------------------:::::::----/hMNNNNNNNNNNNNNNNNNNNNNNNNNNNNmdmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNd+..-.-------------------...........................```                                               
 ````....-------------------------------------------....:yMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNy-..--------------------...........................```                                               
```.....-------------------------------------------.....-sNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNd+..--------------------...........................`````````````                                     
.......--------------------------------------------......+mNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNy++++ymNNNNNNNNNNNNNNNNNNNNNNNNNNs..-------------:::----...........................```````````````                                   
.......-----------------::::::::::::::::-----------....../hNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNy-...-/sdNMNNNNNNNNNNNNNNNNNNNNNms..-------::::::::::---......................................````                                   
.........-----------:::::::::::::::::::::----------......:sNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNm/......:smmmNNNNNNNNNNNNNNNNNNmh+..---::::::::::::::---.......................................```                                   
..............----::::::::::::::::::::::::::::------......-:oyhhmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMs:.......-://+osyhhhddddhhyyo/:..----:::::::::::::::----......................................```                                   
..............----::::::::::::::::::::::::::::-----...........--:/+sdNNNNNNNNNNNNNNNNNNNNNNNNNNNNMh/...............-----------.....----:::::::::::::::----......................................```                                   
...............---:::::::::::::::::::::::::::------................-+hmNNNNNNNNNNNNNNNNNNNNNNNNNNMh:................................---:::::::::::::::----......................................```                                   
................-----------------------------------..................-+ydmNNNNNNNNNNNNNNNNNNNNNNNmy-................................----------::----------......................................```                                   
````````````......--------------------------------......................-/+oyhdmNNNNNNNNNNNNNmhs+:-................................----------------------.......................................```                                   
```````````````....--------..................................................--:::::::::::::::--...............................................................................................````                                   
             ````...................................................................................................................````.........```````````````````````````````````````````````````                                  
               ````````....`.......................................................................................................````````````````````` `````````````````````````````````````````                                    
                     `````````.....................................................................................................`````````````````````````````````````````                     
